/**
    This file is autogenerated using the command `yarn app-store --watch`. It automatically runs when using `yarn dx` 
    Don't modify this file manually.
**/
const applecalendar_api = import("./applecalendar/api");
const caldavcalendar_api = import("./caldavcalendar/api");
const giphy_api = import("./giphy/api");
const googlecalendar_api = import("./googlecalendar/api");
const hubspotothercalendar_api = import("./hubspotothercalendar/api");
const huddle01video_api = import("./huddle01video/api");
const jitsivideo_api = import("./jitsivideo/api");
const metamask_api = import("./metamask/api");
const office365calendar_api = import("./office365calendar/api");
const office365video_api = import("./office365video/api");
const slackmessaging_api = import("./slackmessaging/api");
const spacebooking_api = import("./spacebooking/api");
const stripepayment_api = import("./stripepayment/api");
const tandemvideo_api = import("./tandemvideo/api");
const vital_api = import("./vital/api");
const wipemycalother_api = import("./wipemycalother/api");
const zapier_api = import("./zapier/api");
const zoomvideo_api = import("./zoomvideo/api");
export const apiHandlers = {
applecalendar:applecalendar_api,
caldavcalendar:caldavcalendar_api,
giphy:giphy_api,
googlecalendar:googlecalendar_api,
hubspotothercalendar:hubspotothercalendar_api,
huddle01video:huddle01video_api,
jitsivideo:jitsivideo_api,
metamask:metamask_api,
office365calendar:office365calendar_api,
office365video:office365video_api,
slackmessaging:slackmessaging_api,
spacebooking:spacebooking_api,
stripepayment:stripepayment_api,
tandemvideo:tandemvideo_api,
vital:vital_api,
wipemycalother:wipemycalother_api,
zapier:zapier_api,
zoomvideo:zoomvideo_api,
};